#-------------------------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See https://go.microsoft.com/fwlink/?linkid=2090316 for license information.
#-------------------------------------------------------------------------------------------------------------

version: '3.7'
services:
  rover:

    container_name: rover
    
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - versionRover=aztfmod/roverdev:2010.190123
        - versionPacker=1.6.4

    volumes:
      - ..:/tf

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done" 
    