parameters:
  name: ''
  subscriptionEndpoint: ''
  containerRegistry: ''
  dockerfile: '**/docker-compose.yml'
  buildArgs: ''

jobs:
  - job: Build_container_${{ parameters.name }}
    displayName: Build container ${{ parameters.name }}
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: DockerCompose@0
        displayName: Build ${{ parameters.name }}
        inputs:
          action: 'Build services'
          azureSubscriptionEndpoint: ${{ parameters.subscriptionEndpoint }}
          azureContainerRegistry: ${{ parameters.containerRegistry }}
          workingDirectory: ${{ parameters.buildContext }}
          dockerComposeFile: ${{ parameters.dockerfile }}
          additionalImageTags: $(Build.BuildId)
          ${{ if ne(parameters.buildArgs, '') }}:
            arguments: ${{ parameters.buildArgs }}

      - task: DockerCompose@0
        displayName: Push ${{ parameters.name }}
        inputs:
          action: Push services
          azureSubscriptionEndpoint: ${{ parameters.subscriptionEndpoint }}
          azureContainerRegistry: ${{ parameters.containerRegistry }}
          dockerComposeFile: ${{ parameters.dockerfile }}
          additionalImageTags: $(Build.BuildId)
          includeLatestTag: true
